### ISSUE TITLE
Detail Checklist for CN 2

### ISSUE THREAD

**Issue by nglphucvinh** [nglphucvinh/Checklist-for-CN-2#1]
**Things to do:**

- [x] Define Network Structure for the Building - Bảo & Vinh

  - [x] Define Specification
  - [x] Define High Network Load Area
  - [x] Define suitable Network Architecture for the design, explain why
  - [x] Pay attention to the use of Wireless, Firewall, DMZ

- [x] Equipment List, IP and Cabling Table - Bảo

  - [x] Equipment Lists and their Specification
  - [x] Physical Design
  - [x] WAN connection between HQ and Branches

- [x] Calculate Bandwidth, Throughput - Bảo

- [x] Design Network Flow using GNS 3 - Bảo & Vinh

- [x] Test with ping, traceroute, in the simulated environment - Bảo

- [x] Verify consistency of the network - Vinh

  - [x] Verify reliability, adaptability, security, 

  - [x] Drawbacks 

  - [x] Expansion in the future

- [x] Hand in simulation file - Bảo & Vinh

- [x] Write a report - Vinh

**Comment by nglphucvinh** [comment]
Assignment is done!
